
CREATE DATABASE temp1;
create database temp2 ;
CREATE DATABASE College;

DROP DATABASE temp1;
DROP DATABASE temp2;

USE College;

CREATE TABLE student(
id INT PRIMARY KEY,
name VARCHAR(50),
age INT NOT NULL
);
INSERT INTO student VALUES(1,"ELI",22);
INSERT INTO student VALUES(2,"PAMI",23);
INSERT INTO student VALUES(3,"SUMI",28);
INSERT INTO student VALUES(4,"LUSI",25);
INSERT INTO student VALUES(5,"LARENS",23);

SELECT * FROM student;

CREATE DATABASE college;
CREATE DATABASE IF NOT EXISTS college;

DROP DATABASE company;
 
SHOW DATABASES;
SHOW TABLES;


CREATE TABLE department(
id INT PRIMARY KEY,
name VARCHAR(50)
);

SELECT * FROM department;
INSERT INTO department (id,name) VALUES
(101,"ELI"),
(102,"PAMI"),
(103,"SUMI");
INSERT INTO department VALUES(104,"TANIA");

CREATE DATABASE jkctd;
USE jkctd;
CREATE TABLE employee(
id INT PRIMARY KEY,
name VARCHAR(50),
salary DOUBLE
);

INSERT INTO employee VALUES
(1,"ELI",50000),
(2,"PAMI",40000),
(3,"SUMI",30000);
SELECT * FROM employee;
INSERT INTO employee VALUES
(4,"ELI",50000); 
CREATE TABLE temp1(
id INT UNIQUE
);
INSERT INTO temp1 VALUES(101);
INSERT INTO temp1 VALUES();
INSERT INTO temp1 VALUES();
INSERT INTO temp1 VALUES(102);
SELECT * FROM temp1;
CREATE TABLE temp2(
id INT UNIQUE,
name VARCHAR(50),
age INT,
city VARCHAR (30),
PRIMARY KEY (id,name)
);
SELECT * FROM temp2;
CREATE TABLE temp3(
temp3_id INT ,
FOREIGN KEY (temp3_id) references temp2(id)
);
CREATE TABLE temp4(
id INT ,
salary INT DEFAULT 25000
);
INSERT INTO temp4 VALUES(101,50000);
INSERT INTO temp4 VALUES(102,40000);
INSERT INTO temp4 (id)VALUES(103);
INSERT INTO temp4 VALUES(104,10000);
SELECT * FROM temp4;
CREATE TABLE temp5(
id INT ,
salary INT DEFAULT 25000
);
INSERT INTO temp5 (id) VALUES(103);
SELECT * FROM temp5;
CREATE TABLE city(
id INT UNIQUE,
name VARCHAR(50),
city VARCHAR (30),
age INT CHECK(age>=18)
);
INSERT INTO city VALUES(104,"eli","balasore",22);
CREATE DATABASE GIET;
USE GIET;
CREATE TABLE MCA_2ND_YEAR(
name VARCHAR(50),
rollno INT PRIMARY KEY,
marks INT NOT NULL,
grade VARCHAR(1),
city VARCHAR(20)
);
INSERT INTO MCA_2ND_YEAR(name,rollno,marks,grade,city) VALUES
("FDFDHF",101,78,"C","PUNE"),
("HHIDHF",102,98,"A","PUNE"),
("OILKHF",103,58,"E","PUNE"),
("KHDHF",104,68,"D","PUNE");

SELECT * FROM MCA_2ND_YEAR;

